defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: slurm
- graph: encoder_decoder_only
- model: transformer
- training: default
- _self_


config_validation: True

dataloader:
  num_workers:
    training: 2
    validation: 2
    test: 2
  batch_size:
    training: 4
    validation: 4
    test: 4
  training:
    start: 1994-01-01
    end: 1994-02-28
  validation:
    start: 1994-03-01
    end: 1994-03-31
  test:
    start: 1994-03-01
    end: 1994-03-31

diagnostics:
  plot:
    frequency:
      batch: 5_000
      epoch: 5
graph:
  nodes:
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.ReducedGaussianGridNodes
        grid: o32

hardware:
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1
  paths:
    output: ./output/
    data: ../data
    graph: ./graph/
  files:
    dataset: dataset.zarr

model:
  num_channels: 128
  processor:
    num_layers: 4
    num_heads: 4
    window_size: 64
  encoder:
    num_heads: 4
  decoder:
    num_heads: 4

training:
  max_steps: 100
