mover:
  name: mpidatamover

directories:
  zarr: ${SCRATCH}/anemoi-house/replay/atmosphere-subsampled/no-log/training.zarr
  cache: ${SCRATCH}/anemoi-house/replay/atmosphere-subsampled/no-log/ufs2arco-cache/training
  logs: ${SCRATCH}/anemoi-house/replay/atmosphere-subsampled/no-log/ufs2arco-logs/training

source:
  name: gcs_replay_atmosphere
  uri: gs://noaa-ufs-gefsv13replay/ufs-hr1/0.25-degree-subsampled/03h-freq/zarr/fv3.zarr
  time:
    start: 1994-01-01T00
    end: 2019-12-31T21
    freq: 3h

  variables:
    # 3D Atmospheric Variables
    - ugrd
    - vgrd
    - dzdt
    - tmp
    - spfh
    # 2D Atmospheric Variables
    - pressfc
    - ugrd10m
    - vgrd10m
    - tmp2m
    - spfh2m
    # Static Variables
    - land_static
    - hgtsfc_static
    # Layer thickness is only included for Finite Volume vertical Regridding
    - delz

transforms:
  fv_vertical_regrid:
    weight_var: delz
    interfaces:
      - 0
      - 50
      - 100
      - 150
      - 200
      - 250
      - 300
      - 350
      - 400
      - 450
      - 500
      - 550
      - 600
      - 650
      - 700
      - 750
      - 800
      - 850
      - 900
      - 950
      - 1000
    use_nearest_interfaces: True
    keep_weight_var: False # drop the layer thickness variable after vertical regridding

target:
  name: anemoi
  sort_channels_by_levels: True

  forcings:
    - cos_latitude
    - sin_latitude
    - cos_longitude
    - sin_longitude
    - cos_julian_day
    - sin_julian_day
    - cos_local_time
    - sin_local_time
    - insolation

  chunks:
    time: 1
    variable: -1
    ensemble: 1
    cell: -1

attrs:
  description: "Data from https://psl.noaa.gov/data/ufs_replay/"
